name: ngrok
version: 1.0.0
slug: ngrok
description: >-
  "An ngrok client for Home Assistant"
init: false
webui: http://[HOST]:[PORT:4040]
url: https://github.com/martinwheeler/hassio-addons/ngrok
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
boot: auto
ports:
  4040/tcp: "4040"
ports_description:
  4040/tcp: Web interface
options:
  log_level: info
  auth_token: ""
  region: au
  tunnels:
    - name: homeassistant
      proto: http
      addr: 8123
      inspect: false
schema:
  version: 2
  log_level: list(crit|warn|error|info|debug)
  auth_token: str?
  region: list(au|eu|ap|us|sa|jp|in)?
  tunnels:
    - name: str
      proto: list(http|tls|tcp)
      addr: match(^((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]):([1-9]|[1-5]?[0-9]{2,4}|6[1-4][0-9]{3}|65[1-4][0-9]{2}|655[1-2][0-9]|6553[1-5]))|([1-9]|[1-5]?[0-9]{2,4}|6[1-4][0-9]{3}|65[1-4][0-9]{2}|655[1-2][0-9]|6553[1-5])$)
      inspect: bool?
      host_header: str?
      bind_tls: bool?
      subdomain: str?
      hostname: str?
      crt: str?
      key: str?
      client_cas: str?
      remote_addr: match(^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]):([1-9]|[1-5]?[0-9]{2,4}|6[1-4][0-9]{3}|65[1-4][0-9]{2}|655[1-2][0-9]|6553[1-5])$)?
      metadata: str?
